[package]
name = "trie"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = 's'
panic = "abort"
strip = "symbols"

[lib]
crate_type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.21.1"
